language: cpp
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - build-essential
    - libbluetooth-dev
    - libudev-dev
    - libusb-1.0-0-dev
env:
  matrix:
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="amd64" MAIN_BUILD="true"
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
matrix:
  exclude:
  - os: osx
    env: PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
before_install:
- PACKAGER_URL="https://meshblu-connector.octoblu.com/tools/packager/latest"
- curl -fsS "${PACKAGER_URL}/travis_install_node.sh" -o /tmp/travis_install_node.sh
- chmod +x /tmp/travis_install_node.sh
- ". /tmp/travis_install_node.sh"
- if [ "$TRAVIS_OS_NAME" == "linux" -a "$MAIN_BUILD" == "true" ]; then export NPM_PUBLISH="true"; fi
install:
- npm install --build-from-source
script:
- npm test
before_deploy:
- npm prune --production
- npm install meshblu-connector-packager
- npm dedupe
- npm install -g flatten-packages
- flatten-packages
- npm run generate:package
- npm run generate:schema
- cp schemas.json deploy
deploy:
- provider: releases
  api_key:
    secure: "ryyOFdcQeq/gtpsrDBNU2mFQ9510/tWb7VghbvPI2odwnsj6SEVm27xKi2J9ZD/8cQxzKNf4eubf+DqdJxNJscKg2YXBLXXcbwAIeFH3VrrXaDCiB7CtfPv6qKQdzu52RqQxeKPEhtIGT1aHFghNQhXlD83z49ipP1EcASZ8e3Vevry8QPkrlqahV7PK/ni9y5x58TefVpYqgXHWEGGsODnVBCajT8bbHwzvNKF3jicXusb2f6pNv67D6vCqLCDjvjdS7xTU++ZICZJSbvGjNUMGljHiGrbj5jx+CvEr4oiM6x/UR4XSXtQ2yFCLg2K9YZ4eJpqFRV9UnWomuX2dsiNh8vQQMpllcxNVWWloSNggyORjJ0KTaB997BhRlwp7v1YSjvfmnMmFFDArSPpJcTZhGVWWavHt+bn3hheoNEBT5v0z7gQi/Z1uudLfVG8kwcPRYfGgdvMt48p7rDknBj/0ZAkT/Z2M7ybxyoMeM02uk3SUo82K/9hGbZQ9RqkPnTu+sisCnIJ1cZ8UvyVbEf+mkrNjRbcURI3jHnVMkoF0XeS7RRgOhgN/TI6iyOmPmzJqriBJ3HgD5SYQTLsYLpR/NCjQsTT4YRr2D6c08InvUpaC0eAczeJSaaDpLyxe/XTyrkpIs2W5GZaVnM5T+vbuMZUstX/cOzVuxETlIJw="
  file_glob: true
  file:
  - "deploy/*"
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: "PzduztY2yx6fr43DVDZB+kgOjTrkRdd/mNdEIWLf1yXh83ahnkBam9lIkP9tyBKRXU7vo8x7e94TLDXZKcjl5LhOsZsEjdUxlqqbPeElG+MnuuaSe1DHMIGdUi0xmmtu9HoSIpyQSI/EvU90shDGyyR8eMe6SdnyUomv8dnk//BzOHqfJhcLZ+sLqdoRwVrAWDIPs2itB5STEiW03ey/m2rkG8uffVFDodPYkMqQsuY7PsCmorZfharpWDZOJNtjHjBvz1S7H98gVyJV8z1H/mLvdUaSk+KKn/sJwFDQ8NoNA91iqLUuKToV8/eP1xWo2GQiIPciLoBPg6jnyA8lVUBivo1Yd8zAp+OYTC++ClisI+tag663bXJzt4B7AqZH71C6553axQpAzzIZUiz7UQMNiggEG3mkJir230UBU13NBXYcWdvQoMN3JIOGD1qu/nAyuMaYTGcT4oonIIUYihS/7hXEmudg8t05S4KMjL87ULtGE5xLhzduVou9ZEeQI2JhGWkKPTJWLRcMoZ+nqSyp2s84ow+cdmISIeA+SVjiTINRcTzW6AO4FHBtCWpoQ5uKtXBnq790eE14UU8t1eKLiSqQXRkay6Ml5mV2xYLEoR+pi966sj8tthbpGv1HFmB+/iIuZWB6B9xFKSmBRXgHuWq/g++//o1EynpJH1A="
  on:
    tags: true
    condition: "$NPM_PUBLISH = true"
branches:
  only:
  - "/^v[0-9]/"
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
